// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmrlfbwgpbwhcvipanlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tcmxmYndncGJ3aGN2aXBhbmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTE2MDksImV4cCI6MjA2MzQ2NzYwOX0.fsAEL2X_IIvRSmMhBqDNTJOvvTkkM3jQ9oFIjmBBUCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);